---
title: "00-Introduction"
author: "Bill"
date: "09/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We have chosen to use the conn.log from the MACCDC 2012 dataset for our analysis. After some exceptionally grim encounters with Wireshark we managed to derive an algorithm which found whether or not each conn.log entry resulted in a Snort alert. The resulting dataset was therefore ripe for classification. Our project has the following overview:

1. We run a random forest classifier on our data using the set of variables which were already present in the conn.log, nothing fancy or interesting.

2. We then enrich the set of variables. Bill has become extremely interested in graph embedding, and enriches the dataset with variables that are the position vectors for a variety of graph embeddings. Chentian has verified Markov Property of various features in the dataset.

3. After our exotic variable enrichment we re-train our random forest on the new dataset.

We will assess whether our enrichment methods 'learnt' anything worthwhile about the data in two ways. The first is seeing whether the performance of our classifier changed significantly. The second is examining a few variable importance metrics for our random forest, and seeing if any of our constructed variables score highly.

